fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.2.1
  hooks:
    - id: add-trailing-comma

- repo: local

  hooks:

    - id: black
      name: black
      entry: black
      language: system
      types: [ python ]
      args: [ --line-length=88, --target-version=py39 ]

    - id: autoflake
      name: autoflake
      entry: autoflake
      language: system
      types: [ python ]
      args: [
        --in-place,
        --remove-all-unused-imports,
        --remove-duplicate-keys,
        --ignore-init-module-imports,
      ]

    - id: isort
      name: isort
      entry: isort
      language: system
      types: [ python ]

    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [ python ]

    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [ python ]

    - id: mypy
      name: mypy
      entry: bash -c 'mypy hash_chunker'
      language: system
      types: [ python ]
      verbose: true
